######################################################################
# This file was generated by c2py 0.0.1rc7. Do not edit.             #
######################################################################

#include <stdio.h>
#include "lrndef.h"
#include "lrnref.h"
#include <signal.h>
