######################################################################
# This file was generated by c2py 0.0.1rc7. Do not edit.             #
######################################################################

# include <stdio.h>
# include "lrnref.h"
# define SAME 0
#  
